title: SevenStarGallery
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
description: _unseen_photograohy_and_visual_culture_berlin
color:
  saturation: 0.3512545
  brandStrength: 0.8596456898376346
  lightness: 0.2114695
  brandColors:
    - '#25064D'
    - '#36175E'
    - '#553285'
    - '#7B52AB'
    - '#9768D1'
  rhythmicContrast: 0.6200717
cta:
  bucket: null
  version: null
  domain: null
name: SevenStarGallery
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0
layout_spectrum: 1
