typography_spectrum: 0.49747
color:
  brandColors:
    - '#fff4e0'
    - '#000000'
    - '#873b6a'
    - '#0198b5'
    - '#5cb4b6'
  brandStrength: 0
  lightness: 0.5625
  saturation: 0.625
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: SevenStarGallery
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: SevenStarGallery
description: _unseen_photograohy_and_visual_culture_berlin
purpose: []
